### ISSUE TITLE
How to add data point labels in chart?

### ISSUE THREAD

**Issue by supaflybro** [jorgemorgado/dashing-barchart#12]
Hi, I want to show the actual value of the bar above the bar using bar charts. How can I do this?
There is a plugin for Chart.js that can show this.
http://www.chartjs.org/samples/latest/advanced/data-labelling.html

**Comment by jorgemorgado** [comment]
Hi @supaflybro. Sorry for the late reply. I have not tried this but the question seems to be outside the scope of the dashing widget. You need to have the [datalabels](https://github.com/chartjs/chartjs-plugin-datalabels) plugin installed (and working). Then, all you need to do is to pass the correct options to the chart (either via a Dashing job or, for example, a curl data post). As long as the chart render options are correct, the graph will be displayed with the labels.
Please let me know if you manage to have this working, but I don't think this is a widget's issue.

**Comment by supaflybro** [comment]
Oh, thanks for your reply! I’ve already figured it out:) you can close this question)
