### ISSUE TITLE
via curl?

### ISSUE THREAD

**Issue by avadhutp** [jorgemorgado/dashing-barchart#4]
@jorgemorgado Do you know how I can pass data using curl? I used this JSON, but to no avail—
`{"title":"July 2016","labels":["1s","2s"],"datasets":[{"label":"This month","data":[1,2]}],"auth_token":""}`

**Comment by terrybonds** [comment]
Try having no spaces in the label in datasets, i.e. "This_month".

**Comment by jorgemorgado** [comment]
Sorry for the (very) late reply. Here's an example I took from another widget where I'm using `curl` to pass data. You will need to adapt that to your needs.

```
VALUE=$(( ( RANDOM % 100 )  + 1 ))

  curl -d '{
    "auth_token": "YOUR_AUTH_TOKEN",
    "width": 700,
    "height": 250,
    "options":
      {
        "labels": ["60s","55s","50s","45s","40s","35s","30s","25s","20s","15s","
        "xmax": 100,
        "ymax": 100
      },
    "data":
      [
        0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0
      ],
      "value": '$VALUE'
    }' \
    http://localhost:3030/widgets/your_widget
```

**Comment by jorgemorgado** [comment]
Hope the my curl suggestion has worked for you @avadhutp. Closing the issue for now.
