### ISSUE TITLE
I want to fill the bar with a Text

### ISSUE THREAD

**Issue by estel1212** [jorgemorgado/dashing-barchart#7]
I try to fill the bar with text on bar_chart.coffee. Is there an idea about this. I already try different way but I still don't get it. some thing like her http://jsfiddle.net/uh9vw0ao/

Thanks, Estel.

**Comment by jorgemorgado** [comment]
I've just released the new version with support for Chat.js v2. You might want to try with this new version. Please refer to the latest documentation of Chart.js
