### ISSUE TITLE
Unable to move the title to top

### ISSUE THREAD

**Issue by hdattada** [jorgemorgado/dashing-barchart#9]
I am unable to move the title to the top for some reason. I have used `$title-position:    top;` and restarted dashing but doesnt seem to reflect the change. Could you please let me know if I am missing something?

**Comment by jorgemorgado** [comment]
That's all you need to do. Here is my change:

``` diff
diff --git a/bar_chart.scss b/bar_chart.scss
index 90b27eb..ca10c31 100644
--- a/bar_chart.scss
+++ b/bar_chart.scss
@@ -8,7 +8,7 @@ $moreinfo-color:    rgba(255, 255, 255, 0.7);
 $updateat-color:    rgba(255, 255, 255, 1);

 // If you want the title at the top, set the position to 'top'
-$title-position:    center;
+$title-position:    top;

 // ----------------------------------------------------------------------------
 // Widget-bar-chart styles
```

And here is the result:

![bar_chart_no_legend](https://cloud.githubusercontent.com/assets/5868856/19263587/54bfe3ac-8f9d-11e6-9205-f7af9af95c6b.png)

Maybe one last information: I'm running my dashboard on Chrome. Haven't tested on any other browser.

**Comment by jorgemorgado** [comment]
I'm closing this issue since there was no reply back from my comment. And since it works as documented it was never really an issue in the first place.
